### PR TITLE
Gists endpoint refactoring and expansion

### PR DESCRIPTION
**Pull request by dannysperling**
Refactoring and fixing the gists endpoint to use the current style. Gists have been refactored, but still working on expanding to have full coverage of the endpoint.

### CODE REVIEW

**Comment by pengwynn** [comment]
Looking good.

**Comment by dannysperling** [comment]
Endpoint should be finished - looks like it's not building because of the issue with comparing strings to Hyperlinks. Is there an easy way to fix that problem?

**Comment by pengwynn** [comment]
@dannysperling It looks like testify [changed behavior][]. :frowning: 

[changed behavior]: https://github.com/stretchr/testify/commit/e22aedd37671fb115be6c0c25129c405cb575cfd#commitcomment-10835078

**Comment by dannysperling** [comment]
@pengwynn I remembered there was one thing I was confused by. In the "CheckStar" method, the API returns a 404 "Not Found" if there is no star on the gist:

https://developer.github.com/v3/gists/#check-if-a-gist-is-starred

That counts as an error in the result, since a 404 is in fact an error message. Right now, I have the test expecting an error in that case, but this seems unclean. Is there a better way to handle this?

Side note: why would any API return a 404 in an expected circumstance? That seems like bad design...

**Comment by pengwynn** [comment]
> That counts as an error in the result, since a 404 is in fact an error message. Right now, I have the test expecting an error in that case, but this seems unclean. Is there a better way to handle this?

@dannysperling I think that's just fine. :+1: 

> Side note: why would any API return a 404 in an expected circumstance? That seems like bad design...

This is actually a pretty common RESTful approach. Though `Not Found` is in the client error range, it's not a bad thing. You're just asking the server for a resource and it's saying "I don't have that". The client can then easily wrap up that logic as a Boolean existence check.

**Comment by feiranchen** [comment]
@dannysperling @pengwynn Bring this back because I noticed that some of the test fixtures are not curl-ed from the API but manually constructed, which I was advice to do. If this was intended feel free to ignore this message.

**Pull request merged**
