### PR TITLE
Add Followers API

### PR DESCRIPTION
**Pull request by obsc**
@pengwynn 

Added functionality for https://developer.github.com/v3/users/followers/
Also added booleans as an additional return just as we discussed.

### CODE REVIEW

**Comment by pengwynn** [comment]
@obsc I dig the boolean returns. How would you feel about updating it to match the new approach we're pioneering over in https://github.com/octokit/go-octokit/pull/85 where each method takes a hyperlink instead of having a field on the service?

**Comment by obsc** [comment]
@pengwynn Refactored to the new approach in #85.

One issue that might need addressing is

	if err != nil {
		return nil, &Result{Err: err}
	}

is never called upon testing atm. Should I add failure tests that try to expand a broken hyperlink to hit 100% test coverage?

**Comment by pengwynn** [comment]
> Should I add failure tests that try to expand a broken hyperlink to hit 100% test coverage?

That sounds awesome and would make @dannysperling really happy.

**Comment by obsc** [comment]
@pengwynn Fixed tests to include a failure test now.

**Comment by pengwynn** [comment]
:sparkles: Thanks!

**Pull request merged**
