### PR TITLE
Add links to the API in documentation

### PR DESCRIPTION
**Pull request by dannysperling**
No code changes - just documentation

### CODE REVIEW

**Comment by feiranchen** [comment]
Looks great! :star2: 
If we can have `@see ` marks then we can update the https://github.com/octokit/go-octokit/blob/master/TODO.md list just like https://github.com/octokit/octokit.rb :+1: 
Elaborated here:
https://github.com/octokit/go-octokit/pull/79

**Comment by dannysperling** [comment]
As per a discussion in person, `@see` notifications have been deemed unnecessary as they are ruby documentation. The `TODO.md` file should be able to be updated automatically without them.

**Comment by feiranchen** [comment]
:+1:

**Comment by pengwynn** [comment]
@dannysperling Looks like we have a merge conflict on this one. Need help resolving that?

**Comment by dannysperling** [comment]
Missed your comment earlier. I've fixed the conflicts and this endpoint should be ready to merge now.

**Pull request merged**
