### PR TITLE
'/milestones' endpoints

### PR DESCRIPTION
**Pull request by GeorgiCodes**
Adds the '{owner}/{repo}/milestones' endpoints as per https://developer.github.com/v3/issues/milestones/

### CODE REVIEW

**Comment by pengwynn** [comment]
@GeorgiCodes :cake: This looks great! 

Were you planning on implementing full CRUD for milestones here or in separate PRs?

**Comment by GeorgiCodes** [comment]
@pengwynn I got excited and opened the PR a bit to soon. Ill add the other endpoints for milestones up and then ask for a review :sparkle:.

**Comment by GeorgiCodes** [comment]
@pengwynn okie doke, thing this is ready for some :eyes: please. Had a blast writing some Go today :dancers:.

**Comment by pengwynn** [comment]
:metal:

**Pull request merged**
